[changelog]
header = """
# Changelog

All notable changes to Kursal are documented here.
The format is based on [Keep a Changelog](https://keepachangelog.com/),
and this project adheres to [Semantic Versioning](https://semver.org/).

---

"""
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}\
{% endfor %}
{% endfor %}
 
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
protect_breaking_commits = true
filter_commits = false
tag_pattern = "v[0-9]*"
topo_order = false
sort_commits = "newest"
commit_parsers = [
  { message = "^feat", group = "<!-- 00 -->Features" },
  { message = "^fix", group = "<!-- 01 -->Bug Fixes" },
  { message = "^perf", group = "<!-- 02 -->Performance" },
  { message = "^refactor", group = "<!-- 03 -->Refactor" },
  { message = "^docs", group = "<!-- 04 -->Documentation" },
  { message = "^test", group = "<!-- 05 -->Testing" },
  { message = "^build", group = "<!-- 06 -->Build" },
  { message = "^ci", group = "<!-- 07 -->CI" },
  { message = "^style", group = "<!-- 08 -->Styling" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore", group = "<!-- 09 -->Miscellaneous" },
  { message = "^revert", group = "<!-- 10 -->Revert" },
]
