[package]
name = "kursal-app"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[lib]
name = "kursal_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
kursal-core = { path = "../../kursal-core", features = ["apiserver"] }
kursal-cli = { path = "../../kursal-cli", default-features = false }

# Tauri
tauri = { workspace = true, features = [
    "protocol-asset",
    "devtools",
    "image-png",
    "tray-icon",
] }
tauri-plugin-clipboard-manager = { workspace = true }
tauri-plugin-deep-link = { workspace = true }
tauri-plugin-dialog = { workspace = true }
tauri-plugin-fs = { workspace = true }
tauri-plugin-notification = { workspace = true }
tauri-plugin-opener = { workspace = true }
tauri-plugin-os = { workspace = true }
tauri-plugin-sharekit = { workspace = true }

# Async
tokio = { workspace = true }
async-trait = { workspace = true }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }

# Errors & logging
anyhow = { workspace = true }
log = { workspace = true }
sentry = { workspace = true }
sentry-panic = { workspace = true }

# Misc
clap = { workspace = true, features = ["derive"] }
rayon = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
kursal-cli = { path = "../../kursal-cli", default-features = false, features = ["tui"] }
tauri-plugin-autostart = { workspace = true }
tauri-plugin-single-instance = { workspace = true }
tauri-plugin-updater = { workspace = true }
tauri-plugin-window-state = { workspace = true }
chrono = { workspace = true }

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
tauri-plugin-barcode-scanner = { workspace = true }
tauri-plugin-biometric = { workspace = true }
tauri-plugin-haptics = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-foundation = { workspace = true, features = [
    "std",
    "NSString",
    "NSUserDefaults",
] }

[target.'cfg(target_os = "ios")'.dependencies]
objc2-foundation = { workspace = true, features = [
    "std",
    "NSFileManager",
    "NSString",
    "NSURL",
] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.19"

[target.'cfg(target_os = "windows")'.dependencies]
webview2-com = { workspace = true }
windows = { workspace = true, features = ["Win32_Foundation"] }