[package]
name = "kursal-cli"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[[bin]]
name = "kursal-relay"
path = "src/main.rs"

[features]
default = ["tui"]
tui = ["dep:ratatui"]

[dependencies]
kursal-core = { path = "../kursal-core", default-features = false }

# Async
tokio = { workspace = true, features = ["signal"] }

# Serialization
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }

# Errors & logging
anyhow = { workspace = true }
log = { workspace = true }

# Network
libp2p = { workspace = true }
axum = { workspace = true }

# CLI
clap = { workspace = true, features = ["derive"] }
ratatui = { workspace = true, optional = true }